// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error)
	DeleteTodo(ctx context.Context, id string) error
	GetTodo(ctx context.Context, id string) (Todo, error)
	GetTodoByTitle(ctx context.Context, title string) ([]Todo, error)
	ListTodos(ctx context.Context) ([]Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
